spring:
  datasource:
    url: jdbc:mysql://localhost:3306/william?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8086
mybatis:
  mapper-locations: classpath:Mapper/*.xml
